# Generated by Django 2.0.5 on 2018-06-03 00:54

from django.db import migrations, models
import django.db.models.deletion
import fasugbaScrumy.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fasugbaScrumy', '0002_auto_20180514_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumyGoalsJS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Scrumy Goals',
            },
        ),
        migrations.CreateModel(
            name='ScrumyStatusJS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Scrumy Status',
            },
        ),
        migrations.CreateModel(
            name='ScrumyUserJS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, validators=[fasugbaScrumy.validators.validate_username_length, fasugbaScrumy.validators.validate_username_alphadigits], verbose_name='User name')),
            ],
            options={
                'verbose_name_plural': 'Scrumy Users',
            },
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='scrumy_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrumystatus', to='fasugbaScrumy.ScrumyStatus'),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='scrumy_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrumygoals', to='fasugbaScrumy.ScrumyUser'),
        ),
        migrations.AddField(
            model_name='scrumygoalsjs',
            name='scrumy_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrumystatus', to='fasugbaScrumy.ScrumyStatusJS'),
        ),
        migrations.AddField(
            model_name='scrumygoalsjs',
            name='scrumy_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrumygoals', to='fasugbaScrumy.ScrumyUserJS'),
        ),
    ]
