# Generated by Django 2.0.5 on 2018-06-03 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fasugbaScrumy', '0003_auto_20180603_0154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrumygoalsjs',
            options={'verbose_name_plural': 'Scrumy Goals JS'},
        ),
        migrations.AlterModelOptions(
            name='scrumystatusjs',
            options={'verbose_name_plural': 'Scrumy Status JS'},
        ),
        migrations.AlterModelOptions(
            name='scrumyuserjs',
            options={'verbose_name_plural': 'Scrumy Users JS'},
        ),
        migrations.AlterField(
            model_name='scrumygoalsjs',
            name='scrumy_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrumystatusjs', to='fasugbaScrumy.ScrumyStatusJS'),
        ),
        migrations.AlterField(
            model_name='scrumygoalsjs',
            name='scrumy_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrumygoalsjs', to='fasugbaScrumy.ScrumyUserJS'),
        ),
    ]
